###
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-time": "2023-04-03T15:58:48Z",
  "data": {
    "root-entity-id": "00163E7AA3BC1ED996D4810506E81340",
    "entity-id": "0206B26232001EDDB3B24503658E1885",
    "Changes": [
      {
        "node": "Account",
        "nodeID": "0206B26232001EDDB3B24503658E1885",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "PartialSystemAdministrativeData/LastChangeDateTime",
            "New": "2023-04-03T15:58:48.4412280Z",
            "Old": "2023-04-03T15:57:04.2515700Z"
          }
        ]
      },
      {
        "node": "Address.Root",
        "nodeID": "0206B26232001EDDB3B24503658E9885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E9885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "ChangeCountNumberValue",
            "New": "1 ",
            "Old": "0 "
          }
        ]
      },
      {
        "node": "Common",
        "nodeID": "0206B26232001EDDB3B24503658E7885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E1885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "BusinessPartnerName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      },
      {
        "node": "Name",
        "nodeID": "0206B26232001EDDB3B24503658FD885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E7885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      }
    ]
  }
}

###
POST http://localhost:4004/restapi/VerifyEventPayload
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-time": "2023-04-03T15:58:48Z",
  "data": {
    "root-entity-id": "0206B26232001EDDB3B24503658E1885",
    "entity-id": "0206B26232001EDDB3B24503658E1885",
    "Changes": [
      {
        "node": "Account",
        "nodeID": "0206B26232001EDDB3B24503658E1885",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "PartialSystemAdministrativeData/LastChangeDateTime",
            "New": "2023-04-03T15:58:48.4412280Z",
            "Old": "2023-04-03T15:57:04.2515700Z"
          }
        ]
      },
      {
        "node": "Address.Root",
        "nodeID": "0206B26232001EDDB3B24503658E9885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E9885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "ChangeCountNumberValue",
            "New": "1 ",
            "Old": "0 "
          }
        ]
      },
      {
        "node": "Common",
        "nodeID": "0206B26232001EDDB3B24503658E7885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E1885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "BusinessPartnerName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      },
      {
        "node": "Name",
        "nodeID": "0206B26232001EDDB3B24503658FD885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E7885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      }
    ]
  }
}

###
POST http://localhost:4004/restapi/VerifyEventPayload
Content-Type: application/json

{
  "specversion": "1.0"
}

### SalesData Event

POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/SalesData.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bcf9-68a0b82b1aa9",
  "event-type": "SalesData.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bcf9-68a0b82b1aa9",
  "event-time": "2023-05-16T09:23:06Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF925CF13E5B060",
    "entity-id": "BD40A79D66FC1EEDBCF925CF13E5B060",
    "Changes": [
      {
        "node": "SalesData",
        "nodeID": "BD40A79D66FC1EEDBCF925CF13E5B060",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "DMOHAPATRA",
        "ChangedFields": [
          {
            "Fieldname": "PaymentMethod",
            "New": "PM1",
            "Old": ""
          },
          {
            "Fieldname": "DeliveryMethod",
            "New": "DM1",
            "Old": ""
          },
          {
            "Fieldname": "SystemAdministrativeData/LastChangeDateTime",
            "New": "2023-05-16T09:23:06.1825310Z",
            "Old": "2023-05-16T09:19:34.8091980Z"
          }
        ]
      }
    ]
  }
}

### Tax ID issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1edd-bcf9-db035a03cc53",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1edd-bcf9-db035a03cc53",
  "event-time": "2023-05-16T09:48:32Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68",
    "entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68"
  }
}

### Address issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-time": "2023-05-18T09:06:26Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68",
    "entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68"
  }
}

### SalesRepCode issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-time": "2023-05-18T09:06:26Z",
  "data": {
    "root-entity-id": "0206B26232001EDDB6A09AF5EDD714F9",
    "entity-id": "0206B26232001EDDB6A09AF5EDD714F9"
  }
}