###
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-time": "2023-04-03T15:58:48Z",
  "data": {
    "root-entity-id": "00163E7AA3BC1ED996D4810506E81340",
    "entity-id": "0206B26232001EDDB3B24503658E1885",
    "Changes": [
      {
        "node": "Account",
        "nodeID": "0206B26232001EDDB3B24503658E1885",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "PartialSystemAdministrativeData/LastChangeDateTime",
            "New": "2023-04-03T15:58:48.4412280Z",
            "Old": "2023-04-03T15:57:04.2515700Z"
          }
        ]
      },
      {
        "node": "Address.Root",
        "nodeID": "0206B26232001EDDB3B24503658E9885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E9885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "ChangeCountNumberValue",
            "New": "1 ",
            "Old": "0 "
          }
        ]
      },
      {
        "node": "Common",
        "nodeID": "0206B26232001EDDB3B24503658E7885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E1885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "BusinessPartnerName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      },
      {
        "node": "Name",
        "nodeID": "0206B26232001EDDB3B24503658FD885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E7885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      }
    ]
  }
}

###
POST http://localhost:4004/restapi/VerifyEventPayload
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "0206b262-3200-1eed-b4c7-0e19c7b9cd5f",
  "event-time": "2023-04-03T15:58:48Z",
  "data": {
    "root-entity-id": "0206B26232001EDDB3B24503658E1885",
    "entity-id": "0206B26232001EDDB3B24503658E1885",
    "Changes": [
      {
        "node": "Account",
        "nodeID": "0206B26232001EDDB3B24503658E1885",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "PartialSystemAdministrativeData/LastChangeDateTime",
            "New": "2023-04-03T15:58:48.4412280Z",
            "Old": "2023-04-03T15:57:04.2515700Z"
          }
        ]
      },
      {
        "node": "Address.Root",
        "nodeID": "0206B26232001EDDB3B24503658E9885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E9885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "ChangeCountNumberValue",
            "New": "1 ",
            "Old": "0 "
          }
        ]
      },
      {
        "node": "Common",
        "nodeID": "0206B26232001EDDB3B24503658E7885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E1885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "BusinessPartnerName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      },
      {
        "node": "Name",
        "nodeID": "0206B26232001EDDB3B24503658FD885",
        "ParentNodeID": "0206B26232001EDDB3B24503658E7885",
        "Modification": "Updated",
        "ChangedBy": "B403675",
        "ChangedFields": [
          {
            "Fieldname": "BusinessPartnerFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "SortingFormattedName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          },
          {
            "Fieldname": "Organisation/Name/FirstLineName",
            "New": "BB BTP Account 3.3",
            "Old": "BB BTP Account 3.2"
          }
        ]
      }
    ]
  }
}

###
POST http://localhost:4004/restapi/VerifyEventPayload
Content-Type: application/json

{
  "specversion": "1.0"
}

### SalesData Event

POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/SalesData.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bcf9-68a0b82b1aa9",
  "event-type": "SalesData.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bcf9-68a0b82b1aa9",
  "event-time": "2023-05-16T09:23:06Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF925CF13E5B060",
    "entity-id": "BD40A79D66FC1EEDBCF925CF13E5B060",
    "Changes": [
      {
        "node": "SalesData",
        "nodeID": "BD40A79D66FC1EEDBCF925CF13E5B060",
        "ParentNodeID": "",
        "Modification": "Updated",
        "ChangedBy": "DMOHAPATRA",
        "ChangedFields": [
          {
            "Fieldname": "PaymentMethod",
            "New": "PM1",
            "Old": ""
          },
          {
            "Fieldname": "DeliveryMethod",
            "New": "DM1",
            "Old": ""
          },
          {
            "Fieldname": "SystemAdministrativeData/LastChangeDateTime",
            "New": "2023-05-16T09:23:06.1825310Z",
            "Old": "2023-05-16T09:19:34.8091980Z"
          }
        ]
      }
    ]
  }
}

### Tax ID issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1edd-bcf9-db035a03cc53",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1edd-bcf9-db035a03cc53",
  "event-time": "2023-05-16T09:48:32Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68",
    "entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68"
  }
}

### Address issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-time": "2023-05-18T09:06:26Z",
  "data": {
    "root-entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68",
    "entity-id": "BD40A79D66FC1EEDBCF9199C6AE2EE68"
  }
}

### SalesRepCode issue
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/Account.Root.Updated",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-type": "Account.Root.Updated",
  "event-type-version": "v1",
  "event-id": "bd40a79d-66fc-1eed-bdab-6944d3096283",
  "event-time": "2023-05-18T09:06:26Z",
  "data": {
    "root-entity-id": "0206B26232001EDDB6A09AF5EDD714F9",
    "entity-id": "0206B26232001EDDB6A09AF5EDD714F9"
  }
}

### UK Sales Org. - Test 01
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
  "specversion": "1.0",
  "type": "/sap.c4c/SalesData.Root.Created",
  "source": "/XAF/sap.c4c/000000000740890287",
  "id": "8bd07b3f-b002-1edd-bfda-7ffd39beba3a",
  "event-type": "SalesData.Root.Created",
  "event-type-version": "v1",
  "event-id": "8bd07b3f-b002-1edd-bfda-7ffd39beba3a",
  "event-time": "2023-05-30T10:23:01Z",
  "data": {
    "root-entity-id": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
    "entity-id": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
    "Changes": [
      {
        "node": "Sales Data",
        "nodeID": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
        "ParentNodeID": "",
        "Modification": "Created",
        "ChangedBy": "DMOHAPATRA",
        "ChangedFields": []
      },
      {
        "node": "DeliveryTerms",
        "nodeID": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
        "ParentNodeID": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
        "Modification": "Created",
        "ChangedBy": "DMOHAPATRA",
        "ChangedFields": []
      },
      {
        "node": "PricingTerms",
        "nodeID": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
        "ParentNodeID": "8BD07B3FB0021EDDBFDA70EBDD4C7801",
        "Modification": "Created",
        "ChangedBy": "DMOHAPATRA",
        "ChangedFields": []
      }
    ]
  }
}

### UK Sales Org. - Test 02
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
    "specversion": "1.0",
    "type": "/sap.c4c/Account.Root.Updated",
    "source": "/XAF/sap.c4c/000000000740890287",
    "id": "8bd07b3f-b002-1edd-bfda-7ffd39beda3a",
    "event-type": "Account.Root.Updated",
    "event-type-version": "v1",
    "event-id": "8bd07b3f-b002-1edd-bfda-7ffd39beda3a",
    "event-time": "2023-05-30T10:23:01Z",
    "data": {
        "root-entity-id": "00163E7A9E771EE990FC67FDC1790AFA",
        "entity-id": "00163E7A9E771EE990FC67FDC1790AFA"
    }
}

### Contact.Root.Created
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
    "specversion": "1.0",
    "type": "/sap.c4c/Contact.Root.Created",
    "source": "/XAF/sap.c4c/000000000740890287",
    "id": "8bd07b3f-b002-1edd-bfd8-4300967bfaab",
    "event-type": "Contact.Root.Created",
    "event-type-version": "v1",
    "event-id": "8bd07b3f-b002-1edd-bfd8-4300967bfaab",
    "event-time": "2023-05-30T08:14:56Z",
    "data": {
        "root-entity-id": "8BD07B3FB0021EDDBFD83DD2039E38D0",
        "entity-id": "8BD07B3FB0021EDDBFD83DD2039E38D0",
        "Changes": [
            {
                "node": "Contact",
                "nodeID": "8BD07B3FB0021EDDBFD83DD2039E38D0",
                "ParentNodeID": "",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "Common",
                "nodeID": "8BD07B3FB0021EDDBFD83DD2039E98D0",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DD2039E38D0",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "Name",
                "nodeID": "8BD07B3FB0021EDDBFD83DD2039F18D0",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DD2039E98D0",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "Role",
                "nodeID": "8BD07B3FB0021EDDBFD83DD203A038D0",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DD2039E38D0",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            }
        ]
    }
}

### Conctac.Root.Updated
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
    "specversion": "1.0",
    "type": "/sap.c4c/Contact.Root.Updated",
    "source": "/XAF/sap.c4c/000000000740890287",
    "id": "8bd07b3f-b002-1edd-bfd8-b31e6477233d",
    "event-type": "Contact.Root.Updated",
    "event-type-version": "v1",
    "event-id": "8bd07b3f-b002-1edd-bfd8-b31e6477233d",
    "event-time": "2023-05-30T08:40:07Z",
    "data": {
        "root-entity-id": "8BD07B3FB0021EDDBFD83DD2039E38D0",
        "entity-id": "8BD07B3FB0021EDDBFD83DD2039E38D0",
        "Changes": [
            {
                "node": "Contact",
                "nodeID": "8BD07B3FB0021EDDBFD83DD2039E38D0",
                "ParentNodeID": "",
                "Modification": "Updated",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": [
                    {
                        "Fieldname": "PartialSystemAdministrativeData/LastChangeDateTime",
                        "New": "2023-05-30T08:40:07.5669080Z",
                        "Old": "2023-05-30T08:14:56.3923020Z"
                    }
                ]
            },
            {
                "node": "Common",
                "nodeID": "8BD07B3FB0021EDDBFD83DD2039E98D0",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DD2039E38D0",
                "Modification": "Updated",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": [
                    {
                        "Fieldname": "Maximum Order Amount",
                        "New": "EUR",
                        "Old": ""
                    },
                    {
                        "Fieldname": "Maximum Order Amount",
                        "New": "100.000000 ",
                        "Old": "0.000000 "
                    },
                    {
                        "Fieldname": "Ecommerce Enabled and Role",
                        "New": "131",
                        "Old": ""
                    }
                ]
            }
        ]
    }
}

### BusinessPartnerRelationship.Root.Created
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
    "specversion": "1.0",
    "type": "/sap.c4c/BusinessPartnerRelationship.Root.Created",
    "source": "/XAF/sap.c4c/000000000740890287",
    "id": "8bd07b3f-b002-1edd-bfd8-4317c54dbab0",
    "event-type": "BusinessPartnerRelationship.Root.Created",
    "event-type-version": "v1",
    "event-id": "8bd07b3f-b002-1edd-bfd8-4317c54dbab0",
    "event-time": "2023-05-30T08:14:56Z",
    "data": {
        "root-entity-id": "8BD07B3FB0021EDDBFD83DDE16CFB8DB",
        "entity-id": "8BD07B3FB0021EDDBFD83DDE16CFB8DB",
        "Changes": [
            {
                "node": "Business Partner Relationship",
                "nodeID": "8BD07B3FB0021EDDBFD83DDE16CFB8DB",
                "ParentNodeID": "",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "ContactPerson",
                "nodeID": "8BD07B3FB0021EDDBFD83DDE16D018DB",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DDE16CFB8DB",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "ContactPersonWorkplaceAddressInformation",
                "nodeID": "8BD07B3FB0021EDDBFD83DDE16D118DB",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DDE16D018DB",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "ContactPersonWorkplaceAddress.EMAIL",
                "nodeID": "8BD07B3FB0021EDDBFD84137524B59DF",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DDE16D118DB",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "ContactPersonWorkplaceAddress.ROOT",
                "nodeID": "8BD07B3FB0021EDDBFD83DDE16D118DB",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DDE16D118DB",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            },
            {
                "node": "ContactPersonWorkplaceAddress.TELEPHONE",
                "nodeID": "8BD07B3FB0021EDDBFD84137524B79DF",
                "ParentNodeID": "8BD07B3FB0021EDDBFD83DDE16D118DB",
                "Modification": "Created",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            }
        ]
    }
}

### BusinessPartnerRelationship.Root.Deleted
POST http://localhost:4004/restapi/EnrichData
Content-Type: application/json

{
    "specversion": "1.0",
    "type": "/sap.c4c/BusinessPartnerRelationship.Root.Deleted",
    "source": "/XAF/sap.c4c/000000000740890287",
    "id": "8bd07b3f-b002-1edd-bff3-75ce3ca9c983",
    "event-type": "BusinessPartnerRelationship.Root.Deleted",
    "event-type-version": "v1",
    "event-id": "8bd07b3f-b002-1edd-bff3-75ce3ca9c983",
    "event-time": "2023-05-31T10:12:40Z",
    "data": {
        "root-entity-id": "8BD07B3FB0021EDDBFD8F232918213ED",
        "entity-id": "8BD07B3FB0021EDDBFD8F232918213ED",
        "Changes": [
            {
                "node": "Business Partner Relationship",
                "nodeID": "8BD07B3FB0021EDDBFD8F232918213ED",
                "ParentNodeID": "",
                "Modification": "Deleted",
                "ChangedBy": "DMOHAPATRA",
                "ChangedFields": []
            }
        ]
    }
}
